// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zmwawnzupgldtnmpzqua.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inptd2F3bnp1cGdsZHRubXB6cXVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NzMyMDEsImV4cCI6MjA2NjQ0OTIwMX0.XCI9TSVUuzASv4BXd8j35WkeOUJ5sfcsr_C5sWDvqCI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);